export const BoardActions = {
  INITIATE_BOARD: 'INITIATE_BOARD',
  UNCOVER_CELL: 'UNCOVER_CELL',
  DOUBLE_CLICK_CELL: 'DOUBLE_CLICK_CELL',
  RIGHT_CLICK_CELL: 'RIGHT_CLICK_CELL',
  CHANGE_LEVEL: 'CHANGE_LEVEL',
  GAME_OVER: 'GAME_OVER',
  INITIATE_DUMMY_BOARD: 'INITIATE_DUMMY_BOARD',
};